server:
  port: 8086
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/easy_shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #支持emoji表情配置
      connectionInitSqls: set names utf8mb4
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.template

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 实体扫描，多个package用逗号或者分号分隔,多模块一定要加classpath* 星号
mybatis-plus:
  type-aliases-package: com.boot.template
  mapper-locations:  classpath*:mapper/*Mapper.xml
  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config.id-type:  2
  # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
  global-config.field-strategy:  2
  # 驼峰下划线转换
  global-config.db-column-underline:  true
  # 刷新mapper 调试神器
  global-config.refresh-mapper:  true
  # 开启查询结果下划线转驼峰
  configuration.map-underscore-to-camel-case: true
  configuration.cache-enabled:  false

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  #    config: classpath:log4j2-dev.xml
  level:
    com.btxg.dao: DEBUG

swagger:
  show: true


#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info
